config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
	before_save { self.email = email.downcase }
    validates :chefname, presence: true, length: { maximum: 30 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }, 
                      uniqueness: { case_sensitive: false }
    has_many :recipes 
    has_secure_password
    validates :password, presence: true, length: { minimum: 5 }                
    
end 

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true, length: { minimum: 5, maximum: 500 }
	belongs_to :chef
	validates :chef_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :set_recipe, only: [:show, :edit, :update]

	def index
		@recipes = Recipe.all 
	end

	def show
	end

	def new
		@recipe = Recipe.new(name:"", description: "")
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.chef = Chef.first # till there's an authentication system
		if @recipe.save
            flash[:success] = "Recipe was created successfully!"
            redirect_to recipe_path(@recipe)
		else
			render 'new'
		end
	end

	def edit	
	end

	def update
		if @recipe.update(recipe_params)
			flash[:success] = "Recipe was updated successfully!"
			redirect_to recipe_path(@recipe)
		else
			render 'edit'
		end
	end

	def destroy
		Recipe.find(params[:id]).destroy
		flash[:success] = "Recipe deleted successfully"
		redirect_to recipes_path
	end


  private

    def set_recipe
    	@recipe = Recipe.find(params[:id])
    end

    def recipe_params
    	params.require(:recipe).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.chefname, class: "rounded-circle")
  end

end

app/views/layouts/_footer.html.erb
  <footer class="primary-footer">
    
    <div class="container">
    <div class="row">
      <div class="col-md-4">	

      </div>
      <div class="col-md-4 center grid">
        <span>
          2020 <small>&copy; jazzari</small>    
          <a href="https://github.com/jazzari">Visit my GitHub</a>
        </span>
      </div>
      <div class="col-md-4 right grid">
        <%= link_to "About", pages_about_path %>
      </div>
    </div>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Chef <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "All recipes", recipes_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Recipes
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create a new recipe", new_recipe_path %>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mynewrecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer' %> 
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1>About MyRecipes</h1>
</div>

<div class="container">
  <h2>What is MyRecipes?</h2>

  <p>MyRecipes is a growing space to share recipes for everyone - from begginers to
  	 skilled chefs - who like to cock and show their best and fun meals.  
  </p>	
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to MyRecipes</h1>
	<h2>The best recipe sharing app!</h2>
	<p>
		<%= link_to "View all recipes", recipes_path, class: "btn btn-danger btn-lg btn-xlarge" %>
	</p>
</div>


  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">

        <h2>Hate doing the Dishes?</h2>

        <p>Whether you like cooking, love it or are indifferent to the task, most of us can agree that washing a lot of pots and pans after dinner is a drag. Wouldn’t it instead be easier if there was really only one? 
        Check out our one-pot meals!</p>
        <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>What's for Dinner?</h2>
        <p>We’ve gathered all of the most-loved, highest-rated dinner recipes in our MyRecipes collection. These yummy dinner ideas are the best of the best!</p>
        <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Master Crucial Skills</h2>
        <p>If you’re just getting started in the kitchen, you may feel overwhelmed or intimidated, but remember that cooking is like anything else: The more you practice, the better you will become. Start by mastering these beginner cooking skills.</p>
        <p><a class="btn btn-secondary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
	<div class="col-md-12">
      <%= form_for @recipe do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2 offset-md-2">
          	<%= f.label :name %>
          </div>
          <div class="col-md-8 offset-md-2">
          	<%= f.text_field :name, class: "form-control", 
          	     placeholder: "Name of recipe", autofocus: true %>
          </div>	
        </div>

        <div class="form-group">
          <div class="control-label col-md-2 offset-md-2">
          	<%= f.label :description %>
          </div>
          <div class="col-md-8 offset-md-2">
          	<%= f.text_area :description, rows: 10, class: "form-control",
          	     placeholder: "Enter steps to create recipe" %>
          </div>	
        </div>

        <div class="form-group">
        	<div class="offset-md-2">
        	  <%= f.submit class: "btn ml-3 btn-primary btn-lg btn-xlarge" %>	
        	</div>
        </div>
      <% end %>

      <div class="col-md-4 offset-md-4 colormatch">
      	[ <%= link_to "Cancel request and return to recipes listing",
      	     recipes_path %> ]
      </div>
	</div>	
</div>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>
<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 100) %>
      </section>
    </div>
    <div class="col-md-8 card bg-light">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <p>
        <span class="quiet"><small>Created 

        <%= time_ago_in_words(recipe.created_at) %> ago</small></span>
      </p> 
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="col-md-8 offset-md-2 card bg-light">
	<h4 class="center description"><strong>Steps : </strong></h4>
	<hr />

	<%= simple_format(@recipe.description) %>
    <hr />
    <div class="col">
	  <div class="float-right">
	    <p class="center">	
		  <em>Created by:</em>
	    </p>

	    <p class="center">
	  	  <%= link_to gravatar_for(@recipe.chef), recipes_path %>
	    </p>

	    <p class="center">
	  	  <small><%= @recipe.chef.chefname.capitalize %></small>
	  	  <div class="text-right">
	  		Created: <%= time_ago_in_words(@recipe.created_at) %> ago.
	  	  </div>
	    </p>
      </div>
      <div class="recipe-actions">
    	<%= link_to "Edit this recipe", edit_recipe_path(@recipe), 
    	  class: "btn btn-xs btn-warning" %>
    	<%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
    	 data: { confirm: "Are you sure you want to delete this recipe?" },
    	 class: "btn btn-xs btn-danger" %>  
    	<%= link_to "Return to recipes listing", recipes_path, 
    	class: "btn btn-xs btn-primary" %> 
      </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
  	<div class="col-md-8 offset-md-2">
  	  <div class="card alert-danger">
  	  	<div class="card-header">
  	  	  <h2 class="card-title">
  	  	    <%= pluralize(obj.errors.count, "error") %> 
    	      prohibited this <%= obj.class %> from being saved:	
  	  	  </h2>
  	  	  <div class="card-body">
  	  	    <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>	
  	  	  </div>
  	    </div>
  	  </div>	
  	</div>
  </div> 
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />